<?php
/**
 * pages/products/includes/data.php
 *
 * All product data hardcoded as PHP arrays.
 * Phase 2: replace each $products array with a DB query.
 *
 * Each product:
 *   id        string   Unique slug, used for filtering & URLs
 *   name      string   Display name
 *   desc      string   Short one-line description
 *   price     string   Display price, e.g. '₱80' or '₱80 – ₱150'
 *   badge     string   Optional badge: 'New' | 'Popular' | 'Sale' | ''
 *   category  string   Matches a key in $categories
 *   tags      array    Extra filter tags ['Stickers','Custom']
 *   icon      string   Lucide icon name (fallback when no image)
 *   iconColor string   CSS color for the icon bg
 *   cta       string   Button label
 *   ctaHref   string   Button href
 *   inStock   bool     false = shows "Out of stock" overlay
 */

/* ── CATEGORIES ─────────────────────────────────────────────────── */
$categories = [
  'all'     => ['label' => 'All Products',   'icon' => 'grid-2x2'],
  'prints'  => ['label' => 'Custom Prints',  'icon' => 'printer'],
  'charms'  => ['label' => 'Charms & Keys',  'icon' => 'key'],
  'tumblers'=> ['label' => 'Tumblers & Mugs','icon' => 'coffee'],
  '3d'      => ['label' => '3D Printing',    'icon' => 'box'],
  'gifts'   => ['label' => 'Gift Sets',      'icon' => 'gift'],
];

/* ── PRODUCTS ────────────────────────────────────────────────────── */
$products = [

  /* ─── Custom Prints ─────────────────────────────── */
  [
    'id'        => 'sticker-sheet',
    'name'      => 'Custom Sticker Sheet',
    'desc'      => 'Full-color die-cut stickers on glossy or matte',
    'price'     => '₱80 – ₱150',
    'badge'     => 'Popular',
    'category'  => 'prints',
    'tags'      => ['Stickers', 'Die-cut', 'Glossy'],
    'icon'      => 'star',
    'iconColor' => 'var(--teal-bg)',
    'iconStroke'=> 'var(--teal-dk)',
    'cta'       => 'Order Stickers',
    'ctaHref'   => '../../builder/keychain.php',
    'inStock'   => true,
  ],
  [
    'id'        => 'poster-print',
    'name'      => 'Custom Poster',
    'desc'      => 'Vibrant full-bleed posters, A4 to A1 sizes',
    'price'     => '₱120 – ₱380',
    'badge'     => '',
    'category'  => 'prints',
    'tags'      => ['Poster', 'Large Format'],
    'icon'      => 'image',
    'iconColor' => 'var(--teal-bg)',
    'iconStroke'=> 'var(--teal-dk)',
    'cta'       => 'Order Poster',
    'ctaHref'   => '#',
    'inStock'   => true,
  ],
  [
    'id'        => 'tarpaulin',
    'name'      => 'Tarpaulin / Streamer',
    'desc'      => 'Birthday, events, opening — any occasion',
    'price'     => '₱180 – ₱450',
    'badge'     => '',
    'category'  => 'prints',
    'tags'      => ['Tarpaulin', 'Events', 'Streamer'],
    'icon'      => 'flag',
    'iconColor' => 'var(--teal-bg)',
    'iconStroke'=> 'var(--teal-dk)',
    'cta'       => 'Order Tarp',
    'ctaHref'   => '#',
    'inStock'   => true,
  ],
  [
    'id'        => 'id-lace',
    'name'      => 'ID Lace / Lanyard',
    'desc'      => 'Sublimation-printed lanyards with custom logo',
    'price'     => '₱55 – ₱90',
    'badge'     => 'New',
    'category'  => 'prints',
    'tags'      => ['Lanyard', 'ID Lace', 'Sublimation'],
    'icon'      => 'credit-card',
    'iconColor' => 'var(--teal-bg)',
    'iconStroke'=> 'var(--teal-dk)',
    'cta'       => 'Order Lanyards',
    'ctaHref'   => '#',
    'inStock'   => true,
  ],
  [
    'id'        => 'photo-print',
    'name'      => 'Photo Print',
    'desc'      => 'High-res prints on glossy or canvas paper',
    'price'     => '₱60 – ₱200',
    'badge'     => '',
    'category'  => 'prints',
    'tags'      => ['Photo', 'Canvas'],
    'icon'      => 'camera',
    'iconColor' => 'var(--teal-bg)',
    'iconStroke'=> 'var(--teal-dk)',
    'cta'       => 'Order Photo',
    'ctaHref'   => '#',
    'inStock'   => true,
  ],

  /* ─── Charms & Keychains ─────────────────────────── */
  [
    'id'        => 'diy-keychain',
    'name'      => 'DIY Keychain',
    'desc'      => 'Build your own with beads, charms & letters',
    'price'     => '₱65+',
    'badge'     => 'Popular',
    'category'  => 'charms',
    'tags'      => ['DIY', 'Keychain', 'Beads'],
    'icon'      => 'key',
    'iconColor' => 'var(--pink-bg)',
    'iconStroke'=> 'var(--pink)',
    'cta'       => 'Design Now',
    'ctaHref'   => '../../builder/keychain.php',
    'inStock'   => true,
  ],
  [
    'id'        => 'diy-bracelet',
    'name'      => 'DIY Bracelet',
    'desc'      => 'Custom bead bracelet with your choice of string',
    'price'     => '₱80+',
    'badge'     => '',
    'category'  => 'charms',
    'tags'      => ['DIY', 'Bracelet', 'Beads'],
    'icon'      => 'circle',
    'iconColor' => 'var(--pink-bg)',
    'iconStroke'=> 'var(--pink)',
    'cta'       => 'Design Now',
    'ctaHref'   => '../../builder/bracelet.php',
    'inStock'   => true,
  ],
  [
    'id'        => 'diy-necklace',
    'name'      => 'DIY Necklace',
    'desc'      => 'Charm necklace — pick your length and beads',
    'price'     => '₱100+',
    'badge'     => '',
    'category'  => 'charms',
    'tags'      => ['DIY', 'Necklace'],
    'icon'      => 'heart',
    'iconColor' => 'var(--pink-bg)',
    'iconStroke'=> 'var(--pink)',
    'cta'       => 'Design Now',
    'ctaHref'   => '../../builder/necklace.php',
    'inStock'   => true,
  ],
  [
    'id'        => 'acrylic-keychain',
    'name'      => 'Acrylic Keychain',
    'desc'      => 'Custom-printed acrylic charm with your design',
    'price'     => '₱120 – ₱180',
    'badge'     => 'New',
    'category'  => 'charms',
    'tags'      => ['Acrylic', 'Custom Print'],
    'icon'      => 'sparkles',
    'iconColor' => 'var(--pink-bg)',
    'iconStroke'=> 'var(--pink)',
    'cta'       => 'Order Acrylic',
    'ctaHref'   => '#',
    'inStock'   => true,
  ],

  /* ─── Tumblers & Mugs ────────────────────────────── */
  [
    'id'        => 'tumbler-sublimation',
    'name'      => 'Sublimation Tumbler',
    'desc'      => 'Wrap-around full-color print on stainless tumbler',
    'price'     => '₱350 – ₱550',
    'badge'     => 'Popular',
    'category'  => 'tumblers',
    'tags'      => ['Tumbler', 'Sublimation', 'Stainless'],
    'icon'      => 'coffee',
    'iconColor' => '#FFF5E0',
    'iconStroke'=> 'var(--orange)',
    'cta'       => 'Order Tumbler',
    'ctaHref'   => '#',
    'inStock'   => true,
  ],
  [
    'id'        => 'mug-custom',
    'name'      => 'Custom Mug',
    'desc'      => 'Ceramic mug with photo or text sublimation',
    'price'     => '₱180 – ₱280',
    'badge'     => '',
    'category'  => 'tumblers',
    'tags'      => ['Mug', 'Ceramic', 'Photo'],
    'icon'      => 'cup-soda',
    'iconColor' => '#FFF5E0',
    'iconStroke'=> 'var(--orange)',
    'cta'       => 'Order Mug',
    'ctaHref'   => '#',
    'inStock'   => true,
  ],
  [
    'id'        => 'bottle-custom',
    'name'      => 'Custom Water Bottle',
    'desc'      => 'Engraved or printed sports bottle',
    'price'     => '₱280 – ₱420',
    'badge'     => '',
    'category'  => 'tumblers',
    'tags'      => ['Bottle', 'Sports', 'Engraved'],
    'icon'      => 'droplets',
    'iconColor' => '#FFF5E0',
    'iconStroke'=> 'var(--orange)',
    'cta'       => 'Order Bottle',
    'ctaHref'   => '#',
    'inStock'   => true,
  ],

  /* ─── 3D Printing ────────────────────────────────── */
  [
    'id'        => '3d-figurine',
    'name'      => '3D Figurine',
    'desc'      => 'Custom mini model of anything you can imagine',
    'price'     => '₱280 – ₱680',
    'badge'     => '',
    'category'  => '3d',
    'tags'      => ['Figurine', '3D Print', 'Custom'],
    'icon'      => 'box',
    'iconColor' => '#F0EEFF',
    'iconStroke'=> 'var(--purple)',
    'cta'       => 'Request Print',
    'ctaHref'   => '#',
    'inStock'   => true,
  ],
  [
    'id'        => '3d-name-stand',
    'name'      => '3D Name Stand',
    'desc'      => 'Desk nameplate — any font, any color filament',
    'price'     => '₱180 – ₱350',
    'badge'     => 'Popular',
    'category'  => '3d',
    'tags'      => ['Name Stand', 'Desk', '3D Print'],
    'icon'      => 'type',
    'iconColor' => '#F0EEFF',
    'iconStroke'=> 'var(--purple)',
    'cta'       => 'Request Print',
    'ctaHref'   => '#',
    'inStock'   => true,
  ],
  [
    'id'        => '3d-logo-object',
    'name'      => '3D Logo Object',
    'desc'      => 'Your brand logo turned into a physical 3D object',
    'price'     => '₱350 – ₱800',
    'badge'     => '',
    'category'  => '3d',
    'tags'      => ['Logo', 'Branding', '3D Print'],
    'icon'      => 'layers',
    'iconColor' => '#F0EEFF',
    'iconStroke'=> 'var(--purple)',
    'cta'       => 'Request Print',
    'ctaHref'   => '#',
    'inStock'   => true,
  ],
  [
    'id'        => '3d-mini-model',
    'name'      => '3D Mini Model',
    'desc'      => 'Architectural miniatures, game pieces, props',
    'price'     => '₱220 – ₱580',
    'badge'     => 'New',
    'category'  => '3d',
    'tags'      => ['Mini Model', 'Architecture'],
    'icon'      => 'mountain',
    'iconColor' => '#F0EEFF',
    'iconStroke'=> 'var(--purple)',
    'cta'       => 'Request Print',
    'ctaHref'   => '#',
    'inStock'   => false,
  ],

  /* ─── Gift Sets ───────────────────────────────────── */
  [
    'id'        => 'gift-birthday',
    'name'      => 'Birthday Gift Set',
    'desc'      => 'Curated bundle — stickers, keychain & printed card',
    'price'     => '₱280 – ₱450',
    'badge'     => 'Popular',
    'category'  => 'gifts',
    'tags'      => ['Birthday', 'Bundle', 'Gift'],
    'icon'      => 'gift',
    'iconColor' => 'var(--lime-bg)',
    'iconStroke'=> 'var(--lime-dk)',
    'cta'       => 'Order Gift',
    'ctaHref'   => '#',
    'inStock'   => true,
  ],
  [
    'id'        => 'gift-graduation',
    'name'      => 'Graduation Set',
    'desc'      => 'Personalized keepsake for the graduate',
    'price'     => '₱350 – ₱550',
    'badge'     => '',
    'category'  => 'gifts',
    'tags'      => ['Graduation', 'Keepsake'],
    'icon'      => 'award',
    'iconColor' => 'var(--lime-bg)',
    'iconStroke'=> 'var(--lime-dk)',
    'cta'       => 'Order Gift',
    'ctaHref'   => '#',
    'inStock'   => true,
  ],
  [
    'id'        => 'gift-pasalubong',
    'name'      => 'Pasalubong Bundle',
    'desc'      => 'Cute take-home tokens for 10+ pcs minimum',
    'price'     => '₱80 – ₱150 / pc',
    'badge'     => '',
    'category'  => 'gifts',
    'tags'      => ['Pasalubong', 'Bulk', 'Souvenir'],
    'icon'      => 'package',
    'iconColor' => 'var(--lime-bg)',
    'iconStroke'=> 'var(--lime-dk)',
    'cta'       => 'Order Bundle',
    'ctaHref'   => '#',
    'inStock'   => true,
  ],
  [
    'id'        => 'gift-event',
    'name'      => 'Event Giveaway Pack',
    'desc'      => 'Branded items for corporate events or parties',
    'price'     => 'Request Quote',
    'badge'     => '',
    'category'  => 'gifts',
    'tags'      => ['Events', 'Corporate', 'Bulk'],
    'icon'      => 'users',
    'iconColor' => 'var(--lime-bg)',
    'iconStroke'=> 'var(--lime-dk)',
    'cta'       => 'Get a Quote',
    'ctaHref'   => '#',
    'inStock'   => true,
  ],
];